global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Kafka JMX Metrics
  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['kafka-server:7071']
    scrape_interval: 10s
    metrics_path: /metrics

  # Filebeat Metrics
  - job_name: 'fluentbit'
    static_configs:
      - targets: ['fluentbit:2020']
    scrape_interval: 10s
    metrics_path: /api/v1/metrics/prometheus

  # Flink Metrics
  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager-1:9249', 'flink-taskmanager-1:9249']
    scrape_interval: 15s

  # ClickHouse Metrics (if you expose them)
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:9363']
    scrape_interval: 30s

  # System Metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s